### ISSUE TITLE
[Windows] broken path launching the installer from disks different from C:

### ISSUE THREAD

**Issue by thesave** [jolie/release_tools#3]
Under Windows, launching the installer "java -jar jolie-x.x.x.jar" from a disk that is different from the one where the OS is installed (or better, if the TEMPs path is set on another disk) , say `C:`, the installer breaks:

```
jolie.InterpreterException: jolie.lang.parse.ParserException: /C:/Users/user/AppData/Local/Temp/jolie_installer_tmp3819762671738887644/installer.ol:24: error: File not found: console.iol. Found token type STRING, token content console.iol
        at jolie.Interpreter.buildOOIT(Interpreter.java:1270)
        at jolie.Interpreter.init(Interpreter.java:1037)
        at jolie.Interpreter.run(Interpreter.java:1112)
        at jolie.Jolie.main(Jolie.java:59)
Caused by: jolie.lang.parse.ParserException: /C:/Users/user/AppData/Local/Temp/jolie_installer_tmp3819762671738887644/installer.ol:24: error: File not found: console.iol. Found token type STRING, token content console.iol
        at jolie.lang.parse.AbstractParser.throwException(AbstractParser.java:197)
        at jolie.lang.parse.OLParser.parseInclude(OLParser.java:714)
        at jolie.lang.parse.OLParser._parse(OLParser.java:202)
        at jolie.lang.parse.OLParser.parse(OLParser.java:183)
        at jolie.Interpreter.buildOOIT(Interpreter.java:1218)
        ... 3 more
```

The problem seems to be on that `/C:/Users/user/AppData/Local/Temp/jolie_installer_tmp3819762671738887644/installer.ol:24:` that tries to reach another disk passing by the "root".

**Comment by mwallnoefer** [comment]
I remember that I ran into a similar issue: Jolie's classpath loader is not able to identify classes on other drives than the installation (= Jolie's) one.
So better stick to installations on the system drive.

@fmontesi correct :)?

**Comment by fmontesi** [comment]
Correct! If anybody found a fix, it would be great. :-)
